name: Go CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'  # Nota: A versão mais recente estável é 1.22 (1.24 ainda não existe)
          cache: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          go mod download
          go install github.com/lib/pq@latest

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./... -v

      # - name: Deploy to Cloud (Placeholder)
      #   if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development')
      #   run: |
      #     echo "Deployment step placeholder"
      #     echo "Actual deployment script would go here"
      #     echo "This step is commented out as cloud infrastructure is not yet ready."
