name: Go CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'  # Versão corrigida (1.24 não existe)
          cache: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          go mod download
          go mod tidy

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./... -v
